### ISSUE TITLE
"sudo apt install ..." does not work

### ISSUE THREAD

**Issue by Oberurseler** [MicrosoftDocs/WSL.de-DE#10]
I installed WSL2 and Ubuntu 18  (under Win10  2004) according to your indications. It works, however I cannot install any of the software I need. The "apt install" ends always wit an error. For example:_

apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)**

or anothe example:

sudo apt install gnuplot-x11
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gnuplot-x11

I may continue with other examples, like "gfortran" ... 

Unfortunately, in this state WSL is not useful for me. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Installieren des Windows-Subsystems für Linux (WSL) unter Windows 10](https://docs.microsoft.com/de-de/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @Oberurseler
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by craigloewen-msft** [comment]
Can you please try running `sudo apt-get update` instead? The first error indicates that you don't have sufficient permissions, and the second error could be caused because the apt package repositories haven't been updated.

**Comment by Oberurseler** [comment]
I installed now gnuplot-qt that works with x11, but needs  setting of DISPLAY . 
I tried to set the DISPLAY, but it did not work:

> $ export DISPLAY=localhost:0.0
> $ xterm
> xterm: Xt error: Can't open display: localhost:0.0
> $
What now?

**Comment by CeciAc** [comment]
Hello, @Oberurseler 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/WSL/issues/758

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
