### ISSUE TITLE
Wrong translation of Distribution

### ISSUE THREAD

**Issue by ffloimair** [MicrosoftDocs/WSL.de-DE#11]
Since distribution is a latin word it is also used as-is in German language, except that it is used with an uppercase 'D' since it is a noun.
Please change "Verteilung" to "Distribution". This term is familiar when working with Linux while Verteilung is not and can cause confusion as well as bad search engine results.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Installieren des Windows-Subsystems für Linux (WSL) unter Windows 10](https://docs.microsoft.com/de-de/windows/wsl/install-win10#update-to-wsl-2)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hallo @ffloimair:

Wir überarbeiten derzeit unseren internen Prozess und die Engineeringpipeline. Das führt leider zu Verzögerungen bei der Verarbeitung Ihres Feedbacks.

Vielen Dank für Ihren Beitrag zu unseren Artikeln und Ihr Verständnis. Wir freuen uns auf Ihre weitere Unterstützung.
