### ISSUE TITLE
Kaputter Link

### ISSUE THREAD

**Issue by haiderchristoph** [MicrosoftDocs/WSL.de-DE#20]
Es scheint der Link für "Updatepaket für den WSL2-Linux-Kernel für x64-Computer" funktioniert nicht mehr.
Die Adresse ist "http://aka.ms/wsl2kernelmsix64"

Ich benötige dieses Updatepaket, kann es aber duch den Link nicht laden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b7a1833a-3461-2d9e-bb1e-de5d0ee3fe33
* Version Independent ID: bd4b2627-60c7-1bfe-7831-1dbde906e287
* Content: [Installieren des Windows-Subsystems für Linux (WSL) unter Windows 10](https://docs.microsoft.com/de-de/windows/wsl/install-win10)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by craigloewen-msft** [comment]
Wir haben diesen Link zuruck geandert! 

Fur jetzt, diese link soll funktionert: https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

Danke fur diese bericht, und entschildegung fur mein Deutsch! 😁

**Comment by haiderchristoph** [comment]
Thank you for looking into this so quick!
I was able to download and install it, so I'm happy 😁

No worries, your German is just fine 👍
