### ISSUE TITLE
Klasse um zu entwickeln

### ISSUE THREAD

**Issue by MrTPYT** [MicrosoftDocs/WSL.de-DE#3]
Dieses Werkzeug von Windows habe ich schon immer gebraucht um zum Beispiel eine Shell in Python zu testen die ich selbst programmiert habe.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f2668f02-b96f-7f16-6fc5-950a1e5f86b9
* Version Independent ID: 75f3a2fb-99bd-0161-28ba-5c86e917f4d5
* Content: [Installieren des Windows-Subsystems für Linux (WSL) unter Windows 10](https://docs.microsoft.com/de-de/windows/wsl/install-win10#feedback)
* Content Source: [WSL/install-win10.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/install-win10.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @MrTPYT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hallo, @MrTPYT,

vielen Dank für Ihr Feedback. Es freut uns, dass Sie mir unserer Dokumentation zufrieden sind.  

Sie können gerne weiterhin Feedback abgeben, damit wir die Servicequalität kontinuierlich verbessern können.  

Mit freundlichen Grüßen  

das Microsoft DOCS International Team
