### ISSUE TITLE
Invalid command line option: --set-default-version

### ISSUE THREAD

**Issue by kitingChris** [MicrosoftDocs/WSL.de-DE#4]
```
PS C:\WINDOWS\system32&gt; wsl --set-default-version 2
Invalid command line option: --set-default-version
Copyright (c) Microsoft Corporation. All rights reserved.

Usage: wsl.exe [Argument] [Options...] [CommandLine]
```

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b19a43be-b16a-d903-b69d-75dffce6c329
* Version Independent ID: f9d4a118-1251-8d6b-43f5-2e64808dc527
* Content: [Installieren von WSL 2](https://docs.microsoft.com/de-de/windows/wsl/wsl2-install#enable-the-virtual-machine-platform-optional-component-and-make-sure-wsl-is-enabled)
* Content Source: [WSL/wsl2-install.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/wsl2-install.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by srvbpigh** [comment]
Hello, @kitingChris
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kitingChris** [comment]
Solved it. Was not on preview build 19041
