### ISSUE TITLE
Keine Links für Ubuntu 18.04 in deutscher Übersetzung

### ISSUE THREAD

**Issue by wald-tq** [MicrosoftDocs/WSL.de-DE#7]
In der deutschen Übersetzung fehlen die Links für Ubuntu 18.04
Diese sind nur im englischen Original: https://docs.microsoft.com/en-us/windows/wsl/install-manual

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7194d104-51d3-f53e-cb6c-2242affb7a22
* Version Independent ID: 3fd655c2-9bb3-67d7-c369-545f38f805d8
* Content: [Manuelles Herunterladen von Windows-Subsystem für Linux (WSL)](https://docs.microsoft.com/de-de/windows/wsl/install-manual#feedback)
* Content Source: [WSL/install-manual.md](https://github.com/MicrosoftDocs/WSL.de-DE/blob/live/WSL/install-manual.md)
* Product: **dev-environment**
* Technology: **windows-subsystem-for-linux**
* GitHub Login: @craigloewen-msft
* Microsoft Alias: **crloewen**

**Comment by wald-tq** [comment]
In the german translation the links for ubuntu 18.04 are missing.

Related: 
https://github.com/MicrosoftDocs/WSL/issues/576
https://github.com/MicrosoftDocs/WSL/issues/585

**Comment by srvbpigh** [comment]
Hello, @wald-tq
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @wald-tq 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team
